import Handlebars from "handlebars";

Handlebars.registerHelper("or", function (arg1, arg2, arg3, options) {
  if (arg1 || arg2 || argg3) {
    return options.fn(this);
  } else {
    return options.inverse(this);
  }
});

const template = `# Automatically Generated by Vagrant Config Generator, see https://github.com/jianan1104/vagrantfile-generator
Vagrant.configure('2') do |config|
  config.vm.box = '{{box}}'
  {{#if ip}}
  config.vm.network "private_network", ip: '{{ip}}'
  {{/if}}
  {{#if hostname}}
  config.vm.hostname = '{{hostname}}'
  {{/if}}
  {{#if provider}}
  config.vm.provider "{{provider}}" do |vb|
  {{#if name}}
    vb.name = '{{name}}'
  {{/if}}
  {{#if cpus}}
    vb.cpus = '{{cpus}}'
  {{/if}}
  {{#if memory}}
    vb.memory = '{{memory}}'
  {{/if}}
  {{#or cpus memory name}}
  end
  {{/or}}
  {{/if}}
end`;

export default template;
